spring:
  application:
    name: Gateway

server:
  port: 8084

client:
  deal:
    url: http://localhost:8081
  statement:
    url: http://localhost:8082

springdoc:
  swagger-ui:
    path: /gateway/api-docs-ui
  api-docs:
    path: /gateway/api-docs

